services:
  postgres:
    container_name: postgres_container
    image: postgres:18.6
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
      AIRFLOW_DB_NAME: ${AIRFLOW_DB_NAME}
      AIRFLOW_DB_USER: ${AIRFLOW_DB_USER}
      AIRFLOW_DB_PASSWORD: ${AIRFLOW_DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./postgres/init-airflow.sh:/docker-entrypoint-initdb.d/init-airflow.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s
    networks:
      - my_docker_network

  airflow:
    container_name: airflow_container
    image: apache/airflow:3.3.2
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@postgres:5432/${AIRFLOW_DB_NAME}
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: ${AIRFLOW_ADMIN_USERNAME}:admin
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_PASSWORDS_FILE: /opt/airflow/simple_auth_manager_passwords.json.generated
      AIRFLOW_ADMIN_USERNAME: ${AIRFLOW_ADMIN_USERNAME}
      AIRFLOW_ADMIN_PASSWORD: ${AIRFLOW_ADMIN_PASSWORD}
      APP_DB_HOST: postgres
      APP_DB_PORT: 5432
      APP_DB_NAME: ${APP_DB_NAME}
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
      PYTHONPATH: /opt/airflow/src
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
      - ./airflow/start-airflow.sh:/opt/airflow/start-airflow.sh:ro
    ports:
      - "8000:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - my_docker_network
    command: ["bash", "/opt/airflow/start-airflow.sh"]
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://localhost:8080/api/v2/monitor/health > /dev/null"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  my_docker_network:
    driver: bridge

volumes:
  postgres_data:
